package it.`is`.all.good.coupon.exception

class UsernameExistsException(message: String) : RuntimeException(message)
